### ISSUE TITLE
add loaders for node_modules css

### ISSUE THREAD

**Issue by seraj** [cullenjett/react-ssr-boilerplate#19]
i can't import css from node_modules.
i try to add loader for node_modules css but it's not worked.

**Comment by cullenjett** [comment]
Hi @seraj, I'll try to find some time to investigate this soon. 

In the meantime, here's a workaround: instead of `import`ing the vendor CSS into your JS files you can utilize the `@import` option for CSS/SCSS to bring them into your app styles. For example:

```css
/* index.css */

/* change this to your vendor css file, make sure you keep the ~ at the start */
@import '~react-day-picker/lib/style.css' 
```

I think you'll probably have to do this inside a `.s?css` file inside of `src/styles`. If you still have some of the starter files then I'd recommend `index.scss` for ease.

**Comment by seraj** [comment]
I used this method. But I thought I could add a loader in webpack to load css like this
`import 'packageName/lib/style.css';`
thanks for replay
