### ISSUE TITLE
Tags change from components after server response

### ISSUE THREAD

**Issue by junibrosas** [cullenjett/react-ssr-boilerplate#21]
Does it support scenarios where you need to change the meta tags from the components after server response? E.g. Change in the meta tag when visiting a single post/article.

**Comment by cullenjett** [comment]
Hey @junibrosas, yep you can dynamically update meta tags. This project has [React Helmet](https://github.com/nfl/react-helmet) built in, you can use it to update anything in the document head. For the initial server request any `<Helmet />` components that are server-rendered will update the server response with the correct tags, and during client-side navigation the `<Helmet />` components will update the document head dynamically. You don't have to do anything special outside of the standard instructions, it should "just work".

I'd be happy to help get you up and running if you read through the docs for React Helmet and don't quite understand how to use it, just holler.

**Comment by junibrosas** [comment]
How about populating meta tags from initial data request? In Next.js  framework, `getInitialProps` is used to request initial data for the page.

**Comment by cullenjett** [comment]
Yeah that is possible, although admittedly the initial data request functionality doesn't feel quite as polished as in Next.js (yet). This project uses a similar idea of a static method (in this case it's called `fetchData`), but instead of the return value being injected as props to the component it gets added to a top-level React context provider and is read using a custom hook called `useServerData`. You can use that to get the data inside a component, then use React Helmet to update the meta tags.

There's a sample component that showcases the initial data request functionality at [src/components/Home.js](https://github.com/cullenjett/react-ssr-boilerplate/blob/master/src/components/Home.js). You can see a simple example of updating meta tags by adding the following:

```diff
import React, { useState } from 'react';
+ import { Helmet } from 'react-helmet';

import { api } from '../api';
import { useServerData } from '../state/serverDataContext';

const Home = () => {
  const serverTodos = useServerData(data => {
    return data.todos || [];
  });
  const [todos, setTodos] = useState(serverTodos);

  return (
    <div>
+      {todos[0] && (
+        <Helmet>
+          <meta name="description" content={todos[0].text} />
+        </Helmet>
+      )}

      ... removed code ...
    </div>
  );
};

Home.fetchData = () => {
  return api.todos.all().then(todos => {
    return {
      todos
    };
  });
};

```

If you make that change and look at the network response in the browser dev tools you should see the meta tag populated with the server-fetched data. 

Where `fetchData` isn't as polished as `getInitialProps` is that it doesn't also run when the component mounts after a client-side transition, so for example if you refresh the page on `/about` and then navigate to `/home` the component doesn't fetch any data. That can be solved using the `useEffect` hook to fetch since that is only ever run client-side, but maybe someday I'll create a cleaner abstraction for initial data so that isn't necessary.

**Comment by junibrosas** [comment]
Awesome! this is what I am looking for. I will dig more into this. Thanks for the response.
