### ISSUE TITLE
Unable to implement the redux with SSR

### ISSUE THREAD

**Issue by imsonujangra** [cullenjett/react-ssr-boilerplate#24]
As you have mentioned in the readme that by replacing the <ServerDataProvider /> with the <Provider /> from react-redux on both the server and the client. I have replaced the ServerDataProvider to Provider for redux but it is not working somehow.

server/renderServerSideApp.js

```
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import { Provider } from 'react-redux';
import reducers from '../src/reducers';
const store = createStore(reducers, {}, applyMiddleware(thunk));

const ServerApp = ({ context, data, location }) => {
  return (
    //<ServerDataProvider value={data}>
    <Provider store={store}>
      <StaticRouter location={location} context={context}>
        <App />
      </StaticRouter>
      </Provider>
    //</ServerDataProvider>
  );
};
```
In server/fetchDataForRender.js file i also pass the store.

```
import createStore from '../helpers/createStore';
const store = createStore();


export const fetchDataForRender = (ServerApp, req) => {
  let data = {};

  return ssrPrepass(<ServerApp data={data} location={req.url} />, element => {
    if (element && element.type && element.type.fetchData) {
      return element.type.fetchData(req,store).then(d => {
        Object.keys(d).forEach(key => {
          if (data[key]) {
            logDuplicateKeyMessage(key, element.type.name);
          }
        });

        data = {
          ...data,
          ...d
        };
      });
    }
  }).then(() => {
    return data;
  });
};
```

But when i start the server it throw some exception in file src/state/serverDataContext.js.
 'useServerData() must be a child of <ServerDataProvider />'. Please help how to implement the redux store in SSR.

**Comment by cullenjett** [comment]
It looks like you're pretty close. To fix that error you'll need to remove the sample use of `useServerData` inside `src/components/Home` -- it no longer works because it requires a parent `ServerDataContext`, and since you're replacing that with Redux's `Provider` that means `useServerData` isn't necessary and doesn't work.

You'll also want to change a couple of things in that code. There are a couple of ways you could do this, but here's the basic idea:

- You only want to create one Redux store on the server, but I see two in your sample code. In `renderServerSideApp` where the `ServerApp` component is defined you can accept `store` as a prop, get rid of the `data` prop, and then in `fetchDataForRender` you can pass the store to `<ServerApp store={store} ... />`

- Your `fetchDataForRender` function should return the state from the store, that way it's passed from the server to the client for rehydration:

```javascript
// ...

export const fetchDataForRender = (ServerApp, req) => {
  return ssrPrepass(<ServerApp data={data} location={req.url} />, element => {
    if (element && element.type && element.type.fetchData) {
      return element.type.fetchData(req, store);
    }
  }).then(() => {
    return store.getState()
  })
};
```

- Then you'll want to make sure you rehydrate the store on the client. In `src/main` you can create a new store (because this file is only run on the client) and initialize it with the data sent down from the server inside `window.__SERVER_DATA__`:

```javascript
// ...

const serverData = window.__SERVER_DATA__;

// make sure your helper function can accept an initialState
const store = createStore(reducers, serverData)

export const main = () => {
  Loadable.preloadReady().then(() => {
    ReactDOM.hydrate(
      <Provider store={store}>
        <BrowserRouter>
          <App />
        </BrowserRouter>
      </Provider>,
      document.getElementById('root')
    );
  });
};
```

That should get you pretty close. Then you should be able to dispatch actions from inside a component's `fetchData` (making sure `fetchData` returns a Promise).

**Comment by imsonujangra** [comment]
thanks @cullenjett for helping me. I have implement the redux in it. So i have create a new route /users in which i have load some user name list using some api call in redux store. If you allow me then i create a pull request so you can check my version.

**Comment by cullenjett** [comment]
That's great, I'm happy we got it working 🎉. 

I appreciate the thought, but I'm not interested in adding Redux to this project. I used to have it included, but decided to pull it out to keep things simple.

**Comment by zilahir** [comment]
@imsonujangra hey there! sorry for bothering, but i am also struggling here a bit, since u've managed to get this to work, would you mind to give me a little help: :) Thank you!
